"""add conversation_id and parent_id to query_logs

Revision ID: d85a577aa4c9
Revises: 04649715e40f
Create Date: 2025-09-08 19:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd85a577aa4c9'
down_revision: Union[str, Sequence[str], None] = '04649715e40f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add conversation_id and parent_id columns to query_logs table."""
    
    # Add conversation_id column
    op.add_column('query_logs', sa.Column('conversation_id', sa.String(36), nullable=True))
    
    # Add parent_id column
    op.add_column('query_logs', sa.Column('parent_id', sa.Integer(), nullable=True))
    
    # Add foreign key constraint for parent_id
    op.create_foreign_key(
        'fk_query_logs_parent_id',
        'query_logs', 'query_logs',
        ['parent_id'], ['id'],
        ondelete='SET NULL'
    )
    
    # Add index for conversation_id
    op.create_index('ix_query_logs_conversation_id', 'query_logs', ['conversation_id'])


def downgrade() -> None:
    """Remove conversation_id and parent_id columns from query_logs table."""
    
    # Drop index
    op.drop_index('ix_query_logs_conversation_id', table_name='query_logs')
    
    # Drop foreign key constraint
    op.drop_constraint('fk_query_logs_parent_id', 'query_logs', type_='foreignkey')
    
    # Drop columns
    op.drop_column('query_logs', 'parent_id')
    op.drop_column('query_logs', 'conversation_id')
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('CLIENT', 'END_USER', name='userrole'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_constraint(None, 'query_logs', type_='foreignkey')
    op.drop_index(op.f('ix_query_logs_conversation_id'), table_name='query_logs')
    op.drop_column('query_logs', 'parent_id')
    op.drop_column('query_logs', 'conversation_id')
    # ### end Alembic commands ###
